name: Vite Build & Deploy to CloudFront

on:
  push:
    branches: [ tarea-03 ]

env:
  AWS_REGION: us-east-2
  CLOUDFRONT_DISTRIBUTION_ID: E14JUL6U79BLI9

jobs:
  build-upload-invalidate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

      -  name: Upload dist as artifact
          uses: actions/upload-artifact@v4
          with:
          name: dist-folder
          path: dist/

      - name: Sync dist folder to S3 bucket
        run: |
          aws s3 sync dist/ s3://programacionweb-tarea-03-sebastiansiquina/ --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E14JUL6U79BLI9 --paths "/*"
