name: Deploy Vite App to AWS

on:
  push:
    branches:
      - assessment-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build and Deploy with Doppler
        run: |
          doppler run -- \
          bash -c "
            npm install &&
            npm run build &&
            aws s3 sync ./dist s3://programacionweb-assessment-01 --delete &&
            aws cloudfront create-invalidation --distribution-id E2SKW0HRJVMSXJ --paths '/*'
          "
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
