name: Deploy Vite App to AWS

on:
  push:
    branches:
      - assessment-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Doppler CLI
        uses: dopplerhq/cli-action@v3
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Deploy to AWS S3 & Invalidate CloudFront
        run: |
          doppler run --project tarea-03 --config prd_producción -- \
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && \
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && \
            aws configure set default.region us-east-2 && \
            aws s3 sync ./dist s3://programacionweb-assessment-01 --delete && \
            aws cloudfront create-invalidation --distribution-id E2SKW0HRJVMSXJ --paths "/*"
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
